export const text = {
  login: 'Login',
  skip: 'skip',
  screen1Text: 'Connecting with different people in the society',
  screen1SubText:
    'You can communicate with the people having same interests and opinion through discussion forms.',
  screen2Text: 'Improve your security experience through simple clicks',
  screen2SubText:
    'You can approve or deny your visitors without informing the guard within the app',
  screen3Text: 'Convey your opinions through polls and survey',
  screen3SubText:
    'Share your thoughts, complaints and opinion through polls and survey',
  welcomeBack: 'Welcome back!',
  loginText: 'Login back to your account',
  forgetText: 'OTP sent to your register email',
  forgotPassword: 'Forgot Password?',
  rememberMe: 'Remember me',
  services: 'Services',
  viewAll: 'View All',
  viewLess: 'View Less',
  visitors: 'Visitors',
  eBilling: 'E-Billing',
  complain: 'Complain',
  eForms: 'E-Forms',
  events: 'Events',
  facilityBooking: 'Facility Booking',
  discussion: 'Discussion',
  ePolling: 'E-Polling',
  announcement: 'Announcement',
  documents: 'Documents',
  calender: 'Calender',
  access: 'Access',
  tutorial: 'Tutorial',
  myUnits: 'My Units',
  emergency: 'Emergency',
  cafeteria: 'Cafeteria',
  notice: 'Notice',
  upcoming: 'Upcoming',
  invities: 'Invities',
  totalVisitors: 'Total Visitors',
  pendingApproval: 'Pending Approval',
  accepted: 'Accepted',
  Name: 'Mir Farasat',
  status: 'Status',
  pending: 'Pending',
  Resolved: 'Resolved',
  LoadShedding: 'Load Shedding',
  GasLoadShedding: 'Gas Load Shedding',
  buildingMaintenance: 'Building Maintenance',
  btnLocation: 'Location',
  problem: 'Problem',
  responseSubmit: 'Response Submitted',
  emergency: 'Emergency',
  submit: 'Submit',
  yourdues: 'Your Dues',
  PayNow: 'Pay Now',
  AddNow: 'Add Now',
  myBuilding: 'My Buliding',
  mainBuilding: 'Main Buliding',
  gym: 'Gym',
  pool: 'Pool',
  parking: 'Parking Area',
  mosque: 'Mosque',
  applynow: 'Apply Now',
  invite: 'Invite',
  addvisitors: 'Visitor Form',
  invitevisitor: 'Invite Visitors',
  done: 'Done',
  FaultyElevator: 'Faulty Elevator',
  community: 'Community',
  myevents: 'My Events',
  master: 'MasterCard',
  visa: 'Visa',
  bank: 'Bank',
  recentpayment: 'Recent Payments',
  pool: 'Pool',
  gym: 'Gym',
  Maintenance: 'Maintenance',
  waterdiscussion: 'Water Discussion',
  electricityissue: 'Electricity Issue',
  gymproblem: 'Gym Problem',
  waterinvoice: 'Water Expenditure Invoice',
  electricinvoice: 'Electricity Expenditure Invoice',
  elevatorinvoice: 'Elevator Problem Invoice',
  maintenanceinvoice: 'Maintenance Invoice',
  bookfacility: 'Book Facility',
  addnew: 'Add New',
  next: 'Next',
  paymentsuccessful: 'Payment Successful',
  invitesuccessful: 'Invite Successful',
  bookingSuccessful: 'Booking Successful',
  feedbackpolling: 'Feedback Recieved',
  addSuccessful: 'Added Successfully',
  sharelink: 'Share Link',
  copylink: 'Copy Link',
  receiptrecieved: 'Receipt Recieved',
  booknow: 'Book Now',
  interested: 'Interested',
  ignore: 'Ignore',
  save: 'save',
  cardverification: 'Card Verification',
  addedSuccessfully: 'Added Successfully',



  //NEW TEXT
  manageSociety:'Manage Society',
  mySociety:'My Society',

};
